import type { Product, CategoryInfo } from "./types";

export const categories: CategoryInfo[] = [
  {
    slug: "podis",
    name: "Podis",
    tamilName: "பொடி",
    description: "Traditional spice powders ground fresh using stone grinders",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 15,
  },
  {
    slug: "pickles",
    name: "Pickles & Thokku",
    tamilName: "ஊறுகாய்",
    description: "Sun-ripened pickles made with cold-pressed gingelly oil",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 10,
  },
  {
    slug: "sweets",
    name: "Sweets",
    tamilName: "இனிப்பு",
    description: "Handcrafted traditional sweets using pure ghee and jaggery",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 7,
  },
  {
    slug: "savouries",
    name: "Savouries",
    tamilName: "காரம்",
    description: "Crispy snacks made with rice flour and traditional recipes",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 7,
  },
  {
    slug: "vadams",
    name: "Vadams & Appalam",
    tamilName: "வடகம்",
    description: "Sun-dried rice crisps and papads made the traditional way",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 12,
  },
  {
    slug: "ready-to-mix",
    name: "Ready-to-Mix",
    tamilName: "கலவை",
    description: "Instant mixes for quick traditional South Indian meals",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 8,
  },
  {
    slug: "vathals",
    name: "Vathals",
    tamilName: "வத்தல்",
    description: "Sun-dried vegetables for authentic South Indian curries",
    image: "/placeholder.svg?height=600&width=600",
    productCount: 4,
  },
];

export const products: Product[] = [
  // PODIS
  {
    id: "podi-001",
    name: "Idly Milagai Podi",
    slug: "idly-milagai-podi",
    description:
      "Our signature spice powder, perfect with idly, dosa, and rice. Stone-ground for authentic taste.",
    longDescription:
      "This is our most beloved recipe, passed down through three generations. Made with handpicked red chillies from Guntur, roasted urad dal, and cold-pressed gingelly oil. Each batch is stone-ground in small quantities to preserve the aromatic oils and ensure maximum freshness.",
    price: 150,
    originalPrice: 180,
    weight: "200g",
    category: "podis",
    tags: ["bestseller", "traditional", "no-preservatives"],
    rating: 4.9,
    reviews: 234,
    image: "/placeholder.svg?height=600&width=600",
    images: [
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
      "/placeholder.svg?height=600&width=600",
    ],
    inStock: true,
    isBestseller: true,
    ingredients: [
      "Red Chillies",
      "Urad Dal",
      "Gingelly Oil",
      "Salt",
      "Asafoetida",
    ],
    shelfLife: "6 months",
    storageInfo: "Store in a cool, dry place. Keep refrigerated after opening.",
  },
  {
    id: "podi-002",
    name: "Paruppu Podi",
    slug: "paruppu-podi",
    description:
      "Protein-rich lentil powder with mild spices. A nutritious companion for rice.",
    longDescription:
      "Made with a blend of five different dals, slow-roasted to perfection. This protein-packed powder is a staple in every South Indian household, loved by children and adults alike.",
    price: 140,
    originalPrice: 160,
    weight: "200g",
    category: "podis",
    tags: ["protein-rich", "kids-favorite", "no-preservatives"],
    rating: 4.8,
    reviews: 189,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: [
      "Toor Dal",
      "Chana Dal",
      "Urad Dal",
      "Red Chillies",
      "Cumin",
      "Pepper",
      "Gingelly Oil",
    ],
    shelfLife: "6 months",
    storageInfo: "Store in a cool, dry place.",
  },
  {
    id: "podi-003",
    name: "Karuvepillai Podi",
    slug: "karuvepillai-podi",
    description:
      "Aromatic curry leaf powder rich in iron and essential nutrients.",
    longDescription:
      "Fresh curry leaves sourced from our own garden, sun-dried and ground with selected spices. Known for its health benefits including hair growth and digestion improvement.",
    price: 160,
    originalPrice: 190,
    weight: "150g",
    category: "podis",
    tags: ["health", "iron-rich", "traditional"],
    rating: 4.7,
    reviews: 156,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isNew: true,
    ingredients: [
      "Curry Leaves",
      "Urad Dal",
      "Chana Dal",
      "Red Chillies",
      "Gingelly Oil",
    ],
    shelfLife: "4 months",
    storageInfo: "Store in refrigerator for best freshness.",
  },
  {
    id: "podi-004",
    name: "Sambar Podi",
    slug: "sambar-podi",
    description:
      "Aromatic sambar powder with the perfect blend of coriander and spices.",
    longDescription:
      "The secret to a great sambar lies in the powder. Our recipe uses 15 different spices, slow-roasted and ground to perfection. Makes your sambar taste like it was made in a traditional wood-fired kitchen.",
    price: 130,
    originalPrice: 150,
    weight: "200g",
    category: "podis",
    tags: ["essential", "aromatic", "traditional"],
    rating: 4.8,
    reviews: 278,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: [
      "Coriander",
      "Red Chillies",
      "Toor Dal",
      "Fenugreek",
      "Cumin",
      "Pepper",
      "Turmeric",
    ],
    shelfLife: "8 months",
    storageInfo: "Store in an airtight container.",
  },
  {
    id: "podi-005",
    name: "Rasam Podi",
    slug: "rasam-podi",
    description: "Authentic rasam powder for the perfect tangy, peppery rasam.",
    price: 120,
    originalPrice: 140,
    weight: "150g",
    category: "podis",
    tags: ["essential", "comfort-food"],
    rating: 4.6,
    reviews: 145,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Pepper", "Cumin", "Coriander", "Red Chillies", "Toor Dal"],
    shelfLife: "6 months",
    storageInfo: "Store in a cool, dry place.",
  },
  {
    id: "podi-006",
    name: "Puliyodarai Podi",
    slug: "puliyodarai-podi",
    description:
      "Temple-style tamarind rice powder with the authentic prasadam taste.",
    price: 170,
    originalPrice: 200,
    weight: "200g",
    category: "podis",
    tags: ["temple-style", "festive", "traditional"],
    rating: 4.9,
    reviews: 198,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: [
      "Tamarind",
      "Red Chillies",
      "Groundnut",
      "Sesame",
      "Fenugreek",
      "Mustard",
      "Asafoetida",
    ],
    shelfLife: "4 months",
    storageInfo: "Store in refrigerator.",
  },
  // PICKLES
  {
    id: "pickle-001",
    name: "Mango Thokku",
    slug: "mango-thokku",
    description:
      "Tangy grated mango preserve cooked in gingelly oil. A versatile condiment.",
    longDescription:
      "Made with raw mangoes sourced from Andhra Pradesh, grated and slow-cooked with our signature spice blend in cold-pressed gingelly oil. Perfect with curd rice, chapati, or as a sandwich spread.",
    price: 199,
    originalPrice: 220,
    weight: "300g",
    category: "pickles",
    tags: ["popular", "versatile", "no-preservatives"],
    rating: 4.7,
    reviews: 156,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: [
      "Raw Mango",
      "Red Chillies",
      "Gingelly Oil",
      "Mustard",
      "Fenugreek",
      "Salt",
    ],
    shelfLife: "12 months",
    storageInfo: "Store in a cool, dry place. Use dry spoon.",
  },
  {
    id: "pickle-002",
    name: "Lemon Pickle",
    slug: "lemon-pickle",
    description:
      "Zesty lemon pickle with mustard and fenugreek. A tangy delight.",
    price: 180,
    originalPrice: 200,
    weight: "300g",
    category: "pickles",
    tags: ["tangy", "traditional"],
    rating: 4.6,
    reviews: 123,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: [
      "Lemon",
      "Red Chillies",
      "Gingelly Oil",
      "Mustard",
      "Fenugreek",
      "Salt",
      "Turmeric",
    ],
    shelfLife: "12 months",
    storageInfo: "Store in a cool, dry place.",
  },
  {
    id: "pickle-003",
    name: "Avakkai Pickle",
    slug: "avakkai-pickle",
    description: "Authentic Andhra-style raw mango pickle with bold flavors.",
    price: 220,
    originalPrice: 260,
    weight: "350g",
    category: "pickles",
    tags: ["andhra-special", "spicy", "traditional"],
    rating: 4.8,
    reviews: 187,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isNew: true,
    ingredients: [
      "Raw Mango",
      "Red Chilli Powder",
      "Mustard Powder",
      "Fenugreek",
      "Gingelly Oil",
      "Salt",
    ],
    shelfLife: "12 months",
    storageInfo: "Store in a cool, dry place. Keep in sunlight for first week.",
  },
  {
    id: "pickle-004",
    name: "Gongura Thokku",
    slug: "gongura-thokku",
    description:
      "Tangy sorrel leaves preserve, a specialty from Andhra Pradesh.",
    price: 190,
    originalPrice: 220,
    weight: "250g",
    category: "pickles",
    tags: ["andhra-special", "tangy", "unique"],
    rating: 4.7,
    reviews: 134,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: [
      "Gongura Leaves",
      "Red Chillies",
      "Garlic",
      "Gingelly Oil",
      "Mustard",
      "Salt",
    ],
    shelfLife: "6 months",
    storageInfo: "Store in refrigerator after opening.",
  },
  // SWEETS
  {
    id: "sweet-001",
    name: "Mysore Pak",
    slug: "mysore-pak",
    description:
      "Melt-in-mouth ghee delight from the royal kitchens of Mysore.",
    longDescription:
      "Our Mysore Pak is made with pure cow ghee, premium besan, and sugar in the traditional method. Each piece melts in your mouth, leaving behind the rich aroma of ghee. A royal treat for special occasions.",
    price: 299,
    originalPrice: 350,
    weight: "250g",
    category: "sweets",
    tags: ["premium", "ghee-based", "royal"],
    rating: 4.8,
    reviews: 189,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: ["Besan", "Pure Cow Ghee", "Sugar"],
    shelfLife: "15 days",
    storageInfo: "Store in an airtight container. Best consumed fresh.",
  },
  {
    id: "sweet-002",
    name: "Boondi Ladoo",
    slug: "boondi-ladoo",
    description:
      "Soft, melt-in-mouth ladoos made with fine boondi and cardamom.",
    price: 249,
    originalPrice: 280,
    weight: "250g",
    category: "sweets",
    tags: ["festive", "traditional", "popular"],
    rating: 4.7,
    reviews: 167,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Besan", "Sugar", "Ghee", "Cardamom", "Cashews", "Raisins"],
    shelfLife: "20 days",
    storageInfo: "Store in an airtight container.",
  },
  {
    id: "sweet-003",
    name: "Athirasam",
    slug: "athirasam",
    description:
      "Traditional rice and jaggery sweet, crispy outside and soft inside.",
    price: 279,
    originalPrice: 320,
    weight: "300g",
    category: "sweets",
    tags: ["traditional", "festive", "jaggery"],
    rating: 4.9,
    reviews: 145,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isNew: true,
    ingredients: ["Rice Flour", "Jaggery", "Cardamom", "Gingelly Oil"],
    shelfLife: "10 days",
    storageInfo: "Store in an airtight container at room temperature.",
  },
  {
    id: "sweet-004",
    name: "Badusha",
    slug: "badusha",
    description:
      "Flaky, syrup-soaked sweet with a crispy exterior and soft center.",
    price: 269,
    originalPrice: 300,
    weight: "250g",
    category: "sweets",
    tags: ["popular", "festive", "syrup-soaked"],
    rating: 4.6,
    reviews: 132,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Maida", "Sugar", "Ghee", "Cardamom", "Baking Soda"],
    shelfLife: "15 days",
    storageInfo: "Store in an airtight container.",
  },
  // SAVOURIES
  {
    id: "savoury-001",
    name: "Mullu Murukku",
    slug: "mullu-murukku",
    description: "Spiky rice flour spirals, crispy and addictively crunchy.",
    longDescription:
      "Hand-pressed using traditional brass murukku press, our Mullu Murukku is made with rice flour, urad dal flour, and a secret blend of spices. Each piece is perfectly crispy with the right amount of spice.",
    price: 180,
    originalPrice: 200,
    weight: "250g",
    category: "savouries",
    tags: ["bestseller", "crispy", "traditional"],
    rating: 4.9,
    reviews: 312,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: [
      "Rice Flour",
      "Urad Dal Flour",
      "Cumin",
      "Sesame",
      "Butter",
      "Salt",
    ],
    shelfLife: "30 days",
    storageInfo: "Store in an airtight container.",
  },
  {
    id: "savoury-002",
    name: "Thenkuzhal",
    slug: "thenkuzhal",
    description: "Thick, crunchy murukku rings with a subtle sweetness.",
    price: 170,
    originalPrice: 190,
    weight: "250g",
    category: "savouries",
    tags: ["traditional", "crunchy"],
    rating: 4.7,
    reviews: 198,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Rice Flour", "Urad Dal Flour", "Sesame", "Cumin", "Butter"],
    shelfLife: "30 days",
    storageInfo: "Store in an airtight container.",
  },
  {
    id: "savoury-003",
    name: "Ribbon Pakoda",
    slug: "ribbon-pakoda",
    description: "Crispy ribbon-shaped savory with a hint of spice.",
    price: 160,
    originalPrice: 180,
    weight: "200g",
    category: "savouries",
    tags: ["crispy", "snack"],
    rating: 4.6,
    reviews: 145,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Besan", "Rice Flour", "Red Chilli", "Butter", "Ajwain"],
    shelfLife: "30 days",
    storageInfo: "Store in an airtight container.",
  },
  {
    id: "savoury-004",
    name: "Mixture",
    slug: "mixture",
    description: "Classic South Indian mixture with sev, boondi, and nuts.",
    price: 190,
    originalPrice: 220,
    weight: "250g",
    category: "savouries",
    tags: ["popular", "tea-time", "crunchy"],
    rating: 4.8,
    reviews: 234,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: [
      "Sev",
      "Boondi",
      "Peanuts",
      "Curry Leaves",
      "Red Chillies",
      "Cashews",
    ],
    shelfLife: "30 days",
    storageInfo: "Store in an airtight container.",
  },
  // VADAMS
  {
    id: "vadam-001",
    name: "Elai Vadam - Jeera",
    slug: "elai-vadam-jeera",
    description: "Thin rice crisps with cumin, sun-dried for authentic taste.",
    price: 120,
    originalPrice: 140,
    weight: "150g",
    category: "vadams",
    tags: ["traditional", "sun-dried"],
    rating: 4.6,
    reviews: 145,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Rice", "Cumin", "Salt"],
    shelfLife: "6 months",
    storageInfo: "Store in an airtight container. Deep fry before serving.",
  },
  {
    id: "vadam-002",
    name: "Ulundu Appalam",
    slug: "ulundu-appalam",
    description: "Classic urad dal papad, crispy when fried or roasted.",
    price: 130,
    originalPrice: 150,
    weight: "200g",
    category: "vadams",
    tags: ["essential", "crispy"],
    rating: 4.7,
    reviews: 178,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: ["Urad Dal", "Salt", "Pepper", "Asafoetida"],
    shelfLife: "12 months",
    storageInfo: "Store in an airtight container.",
  },
  // READY-TO-MIX
  {
    id: "mix-001",
    name: "Rava Dosa Mix",
    slug: "rava-dosa-mix",
    description: "Instant mix for crispy rava dosa. Just add water and fry.",
    price: 140,
    originalPrice: 160,
    weight: "500g",
    category: "ready-to-mix",
    tags: ["instant", "convenient", "breakfast"],
    rating: 4.7,
    reviews: 189,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    ingredients: [
      "Rava",
      "Rice Flour",
      "Cumin",
      "Pepper",
      "Curry Leaves",
      "Salt",
    ],
    shelfLife: "6 months",
    storageInfo: "Store in a cool, dry place.",
  },
  {
    id: "mix-002",
    name: "Adai Mix",
    slug: "adai-mix",
    description: "Protein-rich multi-dal dosa mix for nutritious breakfast.",
    price: 160,
    originalPrice: 180,
    weight: "500g",
    category: "ready-to-mix",
    tags: ["protein-rich", "healthy", "breakfast"],
    rating: 4.8,
    reviews: 156,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isNew: true,
    ingredients: [
      "Rice",
      "Toor Dal",
      "Chana Dal",
      "Urad Dal",
      "Red Chillies",
      "Curry Leaves",
    ],
    shelfLife: "6 months",
    storageInfo: "Store in a cool, dry place.",
  },
  {
    id: "mix-003",
    name: "Satthu Mavu",
    slug: "satthu-mavu",
    description: "Nutritious multi-grain porridge mix for all ages.",
    price: 180,
    originalPrice: 200,
    weight: "500g",
    category: "ready-to-mix",
    tags: ["healthy", "kids", "nutrition"],
    rating: 4.9,
    reviews: 234,
    image: "/placeholder.svg?height=600&width=600",
    inStock: true,
    isBestseller: true,
    ingredients: ["Ragi", "Rice", "Wheat", "Moong Dal", "Almonds", "Cardamom"],
    shelfLife: "4 months",
    storageInfo: "Store in an airtight container.",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getCategoryBySlug(slug: string): CategoryInfo | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getBestsellers(): Product[] {
  return products.filter((p) => p.isBestseller);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.isNew);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery) ||
      p.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery))
  );
}
