import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import Link from "next/link";
import Image from "next/image";
import {
  Calendar,
  Clock,
  ArrowLeft,
  Facebook,
  Twitter,
  Linkedin,
  ArrowRight,
} from "lucide-react";

// Complete blog posts data with full content
const blogPosts: Record<
  string,
  {
    title: string;
    excerpt: string;
    content: string[];
    author: string;
    date: string;
    readTime: string;
    category: string;
    image: string;
    relatedPosts: string[];
  }
> = {
  "art-of-making-podi": {
    title: "The Art of Making Perfect Podi: A Traditional Guide",
    excerpt:
      "Learn the secrets behind making authentic South Indian podis at home with tips from our master chefs.",
    image: "/images/Blog/Perfect-Podi.png",
    content: [
      "Podi, the quintessential South Indian condiment, is more than just a spice mix—it's a culinary art form passed down through generations. Each family has their own closely guarded recipe, often handed down from grandmother to mother to daughter, with subtle variations that make it uniquely theirs.",
      "The foundation of any great podi lies in the quality of its ingredients. Fresh spices are paramount. Look for chilies that have been sun-dried naturally, giving them a deeper, more complex flavor. The urad dal should be plump and unblemished, while the chana dal adds a nutty sweetness that balances the heat.",
      "The roasting process is where the magic happens. Each ingredient requires different heat levels and timing. Dry red chilies are roasted first until they turn a shade darker and become fragrant—but be careful not to burn them, or your podi will taste bitter. The dals follow, roasted until golden brown, releasing their nutty aroma.",
      "Temperature control is crucial during roasting. Too high, and your spices will burn; too low, and they won't develop their full flavor potential. The ideal approach is medium heat with constant stirring. You'll know the spices are ready when they release their aromatic oils and change color slightly.",
      "Grinding is an art in itself. Traditional stone grinders (attukal) produce a podi with superior texture and taste. The heat generated by electric grinders can sometimes diminish the aromatic oils in the spices. If using an electric grinder, pulse in short bursts and let the mixture cool between grinding sessions.",
      "The texture of your podi depends on personal preference and intended use. A coarser grind works beautifully when mixed with ghee for a dosa accompaniment, while a finer powder is better for coating idlis or mixing into rice. Some families prefer a chunky texture that provides satisfying bursts of flavor.",
      "Salt is added last, and the quantity can make or break your podi. It's always better to start with less and adjust—you can add more, but you can't take it away. Crystal salt ground along with the spices integrates better than table salt added afterward.",
      "Storage is crucial for maintaining freshness. Transfer your podi to an airtight container while it's still warm—this helps create a vacuum seal. Store in a cool, dark place away from moisture. When stored properly, podi can retain its flavor for 2-3 months, though most families find it disappears much sooner!",
      "At House of Kumaran, we honor these traditional methods while ensuring consistency in every batch. Our podis are made in small quantities, roasted to perfection, and ground fresh to preserve the authentic taste of South India.",
    ],
    author: "Lakshmi Sundaram",
    date: "November 25, 2025",
    readTime: "5 min read",
    category: "Recipes",
    relatedPosts: ["health-benefits-pickles", "chettinad-cuisine"],
  },
  "health-benefits-pickles": {
    title: "5 Health Benefits of Traditional South Indian Pickles",
    excerpt:
      "Discover why your grandmother's pickle recipe is not just delicious but also incredibly healthy.",
    image: "/images/Blog/Pickle-benefit.png",
    content: [
      "For generations, South Indian households have been making pickles not just for their incredible taste, but also for their numerous health benefits. Modern science is now validating what our grandmothers always knew—traditional pickles are a powerhouse of nutrition and gut health.",
      "1. Probiotic Powerhouse: Traditional pickles fermented naturally are rich in probiotics—beneficial bacteria that support digestive health. Unlike commercially produced pickles that use vinegar, traditionally fermented pickles develop natural lactic acid bacteria during the aging process. These probiotics help maintain a healthy gut microbiome, improve digestion, and boost immunity.",
      "2. Rich in Antioxidants: The spices used in South Indian pickles—turmeric, mustard seeds, fenugreek, and asafoetida—are loaded with antioxidants. Turmeric contains curcumin, one of nature's most powerful anti-inflammatory compounds. These antioxidants help fight free radicals, reduce inflammation, and may help prevent chronic diseases.",
      "3. Aids in Digestion: The combination of raw mango, lemon, or other vegetables with spices like asafoetida (hing) and ginger creates a digestive aid that stimulates appetite and improves digestion. That's why pickle is traditionally served as an accompaniment to meals—it helps break down food and aids nutrient absorption.",
      "4. Natural Preservative Properties: The oil, salt, and spices used in traditional pickles act as natural preservatives. Unlike processed foods with artificial preservatives, these natural ingredients have been used safely for thousands of years. Mustard oil, commonly used in South Indian pickles, has antibacterial and antifungal properties.",
      "5. Nutrient Preservation: The pickling process actually preserves the nutrients in vegetables and fruits. Raw mangoes pickled at the peak of their season retain their vitamin C content for months. The fermentation process can even increase the bioavailability of certain nutrients.",
      "The key to healthy pickles lies in the traditional preparation method. Mass-produced pickles often use artificial preservatives, excess salt, and vinegar instead of natural fermentation. At House of Kumaran, we follow time-honored recipes—using cold-pressed oils, natural fermentation, and the perfect blend of spices.",
      "A word of caution: while pickles are healthy, moderation is key. Due to their salt content, people with high blood pressure should consume them in limited quantities. Always pair your pickle with a balanced meal for the best health benefits.",
      "Our pickle-making process begins with selecting the finest raw materials—tender raw mangoes from Andhra, fresh lemons from Tamil Nadu, and premium spices sourced directly from farmers. Each batch is made in small quantities, allowed to mature naturally, and packed with care to deliver authentic taste and health benefits to your table.",
    ],
    author: "Dr. Priya Raman",
    date: "November 20, 2025",
    readTime: "4 min read",
    category: "Health",
    relatedPosts: ["art-of-making-podi", "zero-preservative-science"],
  },
  "our-journey": {
    title: "From Chennai to Your Kitchen: Our Journey",
    excerpt:
      "The story of how House of Kumaran went from a small family kitchen to serving thousands across India.",
    image: "/images/Blog/CtoKitchen.png",
    content: [
      "Every great journey begins with a single step—or in our case, a single batch of podi made in a small kitchen in Chennai. This is the story of House of Kumaran, a tale of tradition, perseverance, and an unwavering commitment to authentic flavors.",
      "It all started in 2021, during the pandemic, when families across India were rediscovering home cooking. Our founder, Kumaran, noticed something troubling—people were struggling to find authentic South Indian condiments that tasted like homemade. Store-bought options were either loaded with preservatives or simply didn't capture the essence of traditional recipes.",
      "Kumaran reached back to his roots, to his grandmother's recipes that had been passed down through three generations. These weren't just recipes; they were memories of lazy Sunday mornings with idli and fresh podi, of festive seasons with special pickles, of everyday meals elevated by simple, authentic flavors.",
      "The first batch of podi was made in our family kitchen—just 50 packets, shared among friends and relatives. The response was overwhelming. 'This tastes exactly like what my mother used to make,' said one. 'I haven't tasted anything this authentic in years,' said another. We knew we had something special.",
      "But scaling up while maintaining quality was a challenge. We refused to take shortcuts. No artificial preservatives, no machine grinding that kills the aroma, no compromising on ingredient quality. Instead, we invested in traditional stone grinders, sourced spices directly from farmers, and trained our team in the traditional methods.",
      "The first year was tough. We worked out of a small facility, packing orders till midnight, personally calling customers to ensure satisfaction. But word spread. First within Chennai, then Tamil Nadu, and soon across India. Today, we serve customers in all 28 states.",
      "Growth brought new challenges. How do you maintain consistency when you're making thousands of packets instead of fifty? Our answer: small batches. Even today, each batch of podi is made in limited quantities, tested for taste and aroma, and only then approved for packing. It's slower, yes, but it's the only way to ensure every packet meets our standards.",
      "Along the way, we've stayed true to our core values. Zero artificial preservatives—because that's how our grandmothers made it. Premium ingredients—because quality can't be compromised. Traditional methods—because some things shouldn't change.",
      "Today, House of Kumaran is more than a business. It's a mission to preserve South Indian culinary traditions and share them with the world. Every time you open a packet of our podi or pickle, you're not just tasting a product—you're experiencing generations of culinary wisdom.",
      "Our journey is far from over. We're constantly exploring new products, always guided by tradition and quality. From Chennai to your kitchen, we're grateful for every customer who has joined us on this journey. Here's to many more years of authentic flavors and cherished memories.",
    ],
    author: "Kumaran Sundaram",
    date: "November 15, 2025",
    readTime: "6 min read",
    category: "Story",
    relatedPosts: ["art-of-making-podi", "zero-preservative-science"],
  },
  "summer-recipes": {
    title: "Summer Specials: Cool Recipes with Our Podis",
    excerpt:
      "Beat the heat with these refreshing recipes using our signature podis and chutneys.",
    image: "/images/Blog/Summer-Recipe.png",
    content: [
      "Summer in South India means soaring temperatures, but also some of the most refreshing and flavorful dishes. Our podis and chutneys aren't just for dosas and idlis—they can transform simple ingredients into cool, satisfying summer meals. Here are our favorite summer recipes using House of Kumaran products.",
      "1. Podi Rice Bowl with Cucumber Raita: This is the ultimate summer lunch—quick, cooling, and packed with flavor. Cook your rice and let it cool slightly. Mix in 2 tablespoons of our Idli Podi with a generous drizzle of sesame oil. Top with cool cucumber raita and a handful of fresh curry leaves fried until crispy. The combination of warm, spiced rice with cold raita is pure summer comfort.",
      "2. Buttermilk with Curry Leaves Podi: South India's answer to the summer heat is neer mor (spiced buttermilk). Add a teaspoon of our Curry Leaves Podi to a glass of fresh buttermilk. The subtle spice of the podi, combined with the cooling buttermilk, creates a refreshing drink that aids digestion and keeps you hydrated.",
      "3. Curd Rice with Garlic Podi: Thayir Sadam (curd rice) is the ultimate South Indian comfort food, especially in summer. Make it special by topping with a sprinkle of our Garlic Podi. The gentle heat of the podi cuts through the cool, creamy curd rice perfectly. Add some pomegranate seeds for a burst of sweetness.",
      "4. Raw Mango Pickle Rice: When summer brings an abundance of raw mangoes, this dish becomes a weekly staple. Mix cooled rice with a tablespoon of our Raw Mango Pickle and a little pickle oil. The tangy, spicy pickle transforms plain rice into something extraordinary. Add roasted peanuts for crunch.",
      "5. Podi Salad Dressing: Yes, podi makes an excellent salad dressing! Mix 2 tablespoons of our Peanut Podi with lime juice, a little honey, and sesame oil. Drizzle over a salad of cucumber, tomatoes, and onions. It's a South Indian twist on a summer salad that's both refreshing and filling.",
      "6. Watermelon with Chili Podi: This might sound unusual, but trust us—it's a revelation. Sprinkle a tiny pinch of our Guntur Chili Podi on fresh watermelon cubes. The heat enhances the sweetness of the watermelon. Add a squeeze of lime and a pinch of salt for the perfect summer snack.",
      "7. Cold Noodles with Podi: Give instant noodles a summer makeover. Cook noodles, rinse with cold water, and toss with sesame oil, soy sauce, and a tablespoon of our Sesame Podi. Add julienned cucumber and carrots. Serve cold for a fusion dish that beats the heat.",
      "Summer cooking should be simple and satisfying. These recipes require minimal cooking—perfect for days when you don't want to spend hours in a hot kitchen. Our podis and pickles do the heavy lifting, adding complex flavors without the effort.",
      "Share your summer podi recipes with us on Instagram @houseofkumaran. We love seeing how our community gets creative with our products!",
    ],
    author: "Meera Krishnan",
    date: "November 10, 2025",
    readTime: "3 min read",
    category: "Recipes",
    relatedPosts: ["art-of-making-podi", "health-benefits-pickles"],
  },
  "zero-preservative-science": {
    title: "The Science Behind Zero-Preservative Food",
    excerpt:
      "How we keep our products fresh and flavorful without any artificial preservatives.",
    image: "/images/Blog/Zero-Preservative.png",
    content: [
      "In an age of processed foods and chemical additives, House of Kumaran stands firm on our zero-preservative promise. But how do we keep our products fresh without artificial preservatives? The answer lies in a combination of traditional wisdom and scientific understanding.",
      "Understanding Natural Preservation: Long before refrigeration and chemical preservatives, our ancestors developed ingenious methods to preserve food. These methods—which we still use today—are actually backed by solid science.",
      "The Role of Salt: Salt has been used for food preservation for thousands of years. It works through osmosis, drawing water out of food and creating an environment where bacteria cannot survive. In our pickles, we use carefully measured amounts of salt—enough to preserve, but not so much that it overwhelms the taste. We use natural rock salt, which also adds trace minerals.",
      "Oil as a Barrier: In South Indian preservation, oil isn't just a cooking medium—it's a protective barrier. When we coat pickles in cold-pressed sesame or groundnut oil, we create an anaerobic environment that prevents oxidation and bacterial growth. The key is ensuring every piece is completely submerged. We use traditional wooden paddles to mix, ensuring even coating.",
      "The Power of Spices: Many spices in our recipes aren't just for flavor—they're natural preservatives. Turmeric has powerful antibacterial properties. Mustard seeds contain compounds that inhibit bacterial growth. Fenugreek has antioxidant properties that prevent spoilage. Asafoetida is both antibacterial and aids digestion.",
      "Controlled Moisture Content: Water is the enemy of preservation. That's why our podi-making process focuses on thorough roasting to remove all moisture from ingredients. Each batch is tested for moisture content before packing. Our pickles are made with sun-dried ingredients, further reducing water content.",
      "The Fermentation Factor: Some of our pickles undergo natural fermentation—a process where beneficial bacteria convert sugars into lactic acid. This not only preserves the food but also creates probiotics that aid digestion. This slow, natural process cannot be rushed, which is why we allow our pickles to mature for weeks before packaging.",
      "Quality Packaging: Our airtight packaging prevents moisture and air from entering, extending shelf life naturally. We use food-grade materials that don't leach chemicals into the food. Each package is designed to maintain product integrity from our facility to your kitchen.",
      "The Importance of Handling: Even the best-preserved food can spoil with improper handling. That's why we include handling instructions with every product. Always use a dry spoon—moisture introduction is the most common cause of spoilage in home kitchens.",
      "Our Commitment: Choosing zero-preservative means choosing a shorter shelf life compared to chemically preserved alternatives. But we believe this trade-off is worth it. Our products typically last 2-3 months for podis and 6-8 months for pickles—plenty of time to enjoy them, and a guarantee that you're eating fresh, wholesome food.",
      "The science of natural preservation has been perfected over thousands of years. At House of Kumaran, we're proud to continue this tradition, proving that the best way to preserve food is often the oldest way.",
    ],
    author: "Dr. Anand Krishnamurthy",
    date: "November 5, 2025",
    readTime: "5 min read",
    category: "Behind the Scenes",
    relatedPosts: ["health-benefits-pickles", "our-journey"],
  },
  "chettinad-cuisine": {
    title: "Regional Flavors: Exploring Chettinad Cuisine",
    excerpt:
      "A deep dive into the spicy, aromatic world of Chettinad cooking and its unique ingredients.",
    image: "/images/Blog/Regional-Flavour.png",
    content: [
      "Of all the regional cuisines of South India, Chettinad stands apart for its bold, complex flavors and unique spice blends. Originating from the Chettinad region of Tamil Nadu, this cuisine tells the story of the Nattukotai Chettiars—a merchant community whose travels brought exotic spices and cooking techniques to their homeland.",
      "The Chettiar Legacy: The Chettiars were prominent traders who traveled extensively to Burma, Malaysia, Singapore, and other Southeast Asian countries. They brought back not just wealth, but also rare spices and culinary influences. This history is reflected in Chettinad cuisine's use of ingredients like star anise, mace, and stone flower—uncommon in other South Indian cooking.",
      "The Famous Chettinad Spice Blend: What makes Chettinad food instantly recognizable is its distinctive masala. Unlike other South Indian spice mixes, Chettinad masala includes: Kalpasi (Stone Flower) - a lichen with an earthy, mushroom-like flavor; Marathi Mokku - dried flower pods with a subtle sweetness; Star Anise - adding a gentle licorice note; and generous amounts of black pepper, not just chilies, for heat.",
      "Heat with Depth: Chettinad food is famously spicy, but it's a complex heat. The combination of black pepper, dried chilies, and other spices creates layers of warmth that build gradually. Unlike cuisines that rely on chilies alone, Chettinad food has depth—you can taste each spice distinctly even as they blend harmoniously.",
      "Signature Dishes: Chettinad Chicken (Kozhi Varuval) is the flagship dish—chicken pieces cooked in a rich, dark gravy of freshly ground spices. The meat is traditionally from country chicken, which has a firmer texture. Kavuni Arisi is a black rice pudding sweetened with palm jaggery, traditionally served at weddings. Kuzhambu varieties in Chettinad use more tamarind and are spicier than their counterparts elsewhere in Tamil Nadu.",
      "Cooking Techniques: Chettinad cooking emphasizes freshly ground spices—pre-made masala powders are rarely used in traditional kitchens. Spices are roasted and ground daily, ensuring maximum flavor. Meats are often marinated for hours, sometimes overnight, allowing the spices to penetrate deeply. Clay pots and wood fires are traditional cooking methods that add their own subtle flavors.",
      "Vegetarian Chettinad: While famous for non-vegetarian dishes, Chettinad has a rich vegetarian repertoire. Drumstick sambar, raw banana fry, and various kootu (mixed vegetable) dishes showcase the same bold spicing in vegetarian form. Our Chettinad Podi brings these flavors to your everyday meals.",
      "The Chettinad Kitchen: Traditional Chettinad homes have elaborate kitchens with built-in stone grinders, specialized vessels for different cooking methods, and storage systems for their prized spices. While we can't replicate these kitchens, we can bring Chettinad flavors to modern homes through our products.",
      "Our Chettinad Collection: At House of Kumaran, we've worked with Chettinad home cooks to develop products that capture authentic flavors. Our Chettinad Podi uses traditional spice ratios, including the hard-to-find kalpasi and marathi mokku. It's the closest you can get to Chettinad flavors without visiting Karaikudi.",
      "The Chettinad food philosophy—bold spices, fresh ingredients, time-honored techniques—aligns perfectly with our approach at House of Kumaran. Whether you're familiar with this cuisine or discovering it for the first time, we invite you to explore the rich, aromatic world of Chettinad cooking.",
    ],
    author: "Meenakshi Chettiar",
    date: "October 28, 2025",
    readTime: "7 min read",
    category: "Culture",
    relatedPosts: ["art-of-making-podi", "health-benefits-pickles"],
  },
};

interface BlogPageProps {
  params: Promise<{ slug: string }>;
}

// Generate static params for all blog posts
export function generateStaticParams() {
  return Object.keys(blogPosts).map((slug) => ({
    slug,
  }));
}

// Generate metadata for each blog post
export async function generateMetadata({ params }: BlogPageProps) {
  const { slug } = await params;
  const post = blogPosts[slug];
  if (!post) {
    return {
      title: "Post Not Found | House of Kumaran Blog",
    };
  }
  return {
    title: `${post.title} | House of Kumaran Blog`,
    description: post.excerpt,
  };
}

export default async function BlogPostPage({ params }: BlogPageProps) {
  const { slug } = await params;
  const post = blogPosts[slug];

  if (!post) {
    return (
      <main className="min-h-screen bg-background text-foreground">
        <Navbar />
        <section className="pt-32 pb-20 px-6">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="font-serif text-4xl font-bold mb-4">
              Post Not Found
            </h1>
            <p className="text-foreground/60 mb-8">
              The blog post you&apos;re looking for doesn&apos;t exist.
            </p>
            <Link
              href="/blog"
              className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground font-semibold rounded-full hover:bg-primary/90 transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Blog
            </Link>
          </div>
        </section>
        <Footer />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-background text-foreground">
      <Navbar />

      {/* Header */}
      <section className="pt-32 pb-8 px-6">
        <div className="max-w-3xl mx-auto">
          <Link
            href="/blog"
            className="inline-flex items-center gap-2 text-primary hover:text-primary/80 transition-colors mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Blog
          </Link>

          <span className="inline-block px-3 py-1 bg-primary/20 text-primary text-sm rounded-full mb-4">
            {post.category}
          </span>

          <h1 className="font-serif text-3xl md:text-5xl font-bold mb-6 leading-tight">
            {post.title}
          </h1>

          <div className="flex flex-wrap items-center gap-4 text-sm text-foreground/60">
            <span className="font-medium text-foreground">{post.author}</span>
            <span className="flex items-center gap-1">
              <Calendar className="w-4 h-4" />
              {post.date}
            </span>
            <span className="flex items-center gap-1">
              <Clock className="w-4 h-4" />
              {post.readTime}
            </span>
          </div>
        </div>
      </section>

      {/* Featured Image */}
      <section className="pb-8 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="relative aspect-[2/1] rounded-3xl overflow-hidden">
            <Image
              src={post.image}
              alt={post.title}
              fill
              className="object-cover"
              sizes="(max-width: 1024px) 100vw, 896px"
              priority
            />
            <div className="absolute inset-0 bg-gradient-to-t from-background/40 to-transparent" />
          </div>
        </div>
      </section>

      {/* Content */}
      <section className="pb-12 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="prose prose-lg prose-invert max-w-none">
            {post.content.map((paragraph, index) => (
              <p key={index} className="text-foreground/80 mb-6 leading-relaxed">
                {paragraph}
              </p>
            ))}
          </div>
        </div>
      </section>

      {/* Share Section */}
      <section className="pb-12 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center justify-between py-6 border-t border-b border-border">
            <span className="font-medium">Share this article</span>
            <div className="flex items-center gap-3">
              <a
                href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(
                  `https://houseofkumaran.com/blog/${slug}`
                )}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center hover:bg-primary hover:text-primary-foreground transition-colors"
              >
                <Facebook className="w-5 h-5" />
              </a>
              <a
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(
                  post.title
                )}&url=${encodeURIComponent(
                  `https://houseofkumaran.com/blog/${slug}`
                )}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center hover:bg-primary hover:text-primary-foreground transition-colors"
              >
                <Twitter className="w-5 h-5" />
              </a>
              <a
                href={`https://www.linkedin.com/shareArticle?mini=true&url=${encodeURIComponent(
                  `https://houseofkumaran.com/blog/${slug}`
                )}&title=${encodeURIComponent(post.title)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center hover:bg-primary hover:text-primary-foreground transition-colors"
              >
                <Linkedin className="w-5 h-5" />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Author Bio */}
      <section className="pb-16 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="p-6 bg-card rounded-2xl border border-border">
            <div className="flex items-start gap-4">
              <div className="w-16 h-16 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0">
                <span className="font-serif text-2xl text-primary">
                  {post.author.charAt(0)}
                </span>
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-1">{post.author}</h3>
                <p className="text-foreground/60 text-sm">
                  A passionate food writer and culinary enthusiast exploring the rich heritage
                  of South Indian cuisine. When not writing, you&apos;ll find them in the
                  kitchen experimenting with traditional recipes passed down through generations.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Related Posts */}
      {post.relatedPosts.length > 0 && (
        <section className="py-16 px-6 bg-sidebar">
          <div className="max-w-[1400px] mx-auto">
            <h2 className="font-serif text-2xl font-bold mb-8">
              Related Articles
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              {post.relatedPosts.map((relatedSlug) => {
                const relatedPost = blogPosts[relatedSlug];
                if (!relatedPost) return null;
                return (
                  <Link
                    key={relatedSlug}
                    href={`/blog/${relatedSlug}`}
                    className="group p-6 bg-background rounded-2xl border border-border hover:border-primary/30 transition-colors"
                  >
                    <span className="text-xs text-primary uppercase tracking-wider">
                      {relatedPost.category}
                    </span>
                    <h3 className="font-semibold text-lg mt-2 mb-3 group-hover:text-primary transition-colors">
                      {relatedPost.title}
                    </h3>
                    <p className="text-foreground/60 text-sm line-clamp-2">
                      {relatedPost.excerpt}
                    </p>
                    <span className="inline-flex items-center gap-1 text-primary text-sm mt-4 group-hover:gap-2 transition-all">
                      Read More <ArrowRight className="w-4 h-4" />
                    </span>
                  </Link>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {/* CTA */}
      <section className="py-16 px-6">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="font-serif text-2xl font-bold mb-4">
            Ready to Taste Tradition?
          </h2>
          <p className="text-foreground/60 mb-6">
            Experience the authentic flavors we write about. Shop our collection
            of traditional South Indian products.
          </p>
          <Link
            href="/shop"
            className="inline-flex items-center gap-2 px-6 py-3 bg-primary text-primary-foreground font-semibold rounded-full hover:bg-primary/90 transition-colors"
          >
            Shop Now
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      <Footer />
    </main>
  );
}
