import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import Link from "next/link";
import {
  Calendar,
  Clock,
  ArrowLeft,
  Facebook,
  Twitter,
  Linkedin,
  ArrowRight,
} from "lucide-react";

// Sample blog posts data - in production, this would come from a CMS
const blogPosts: Record<
  string,
  {
    title: string;
    excerpt: string;
    content: string[];
    author: string;
    date: string;
    readTime: string;
    category: string;
    image: string;
    relatedPosts: string[];
  }
> = {
  "art-of-making-perfect-podi": {
    title: "The Art of Making Perfect Podi: A Traditional Guide",
    excerpt:
      "Discover the centuries-old techniques behind crafting the perfect South Indian podi, from selecting spices to achieving the ideal texture.",
    content: [
      "Podi, the quintessential South Indian condiment, is more than just a spice mix—it's a culinary art form passed down through generations. Each family has their own closely guarded recipe, often handed down from grandmother to mother to daughter, with subtle variations that make it uniquely theirs.",
      "The foundation of any great podi lies in the quality of its ingredients. Fresh spices are paramount. Look for chilies that have been sun-dried naturally, giving them a deeper, more complex flavor. The urad dal should be plump and unblemished, while the chana dal adds a nutty sweetness that balances the heat.",
      "The roasting process is where the magic happens. Each ingredient requires different heat levels and timing. Dry red chilies are roasted first until they turn a shade darker and become fragrant—but be careful not to burn them, or your podi will taste bitter. The dals follow, roasted until golden brown, releasing their nutty aroma.",
      "Grinding is an art in itself. Traditional stone grinders (attukal) produce a podi with superior texture and taste. The heat generated by electric grinders can sometimes diminish the aromatic oils in the spices. If using an electric grinder, pulse in short bursts and let the mixture cool between grinding sessions.",
      "The texture of your podi depends on personal preference and intended use. A coarser grind works beautifully when mixed with ghee for a dosa accompaniment, while a finer powder is better for coating idlis or mixing into rice. Some families prefer a chunky texture that provides satisfying bursts of flavor.",
      "Storage is crucial for maintaining freshness. Transfer your podi to an airtight container while it's still warm—this helps create a vacuum seal. Store in a cool, dark place away from moisture. When stored properly, podi can retain its flavor for 2-3 months, though most families find it disappears much sooner!",
    ],
    author: "Lakshmi Sundaram",
    date: "January 15, 2025",
    readTime: "8 min read",
    category: "Recipes",
    image: "/images/blog/podi-making.jpg",
    relatedPosts: [
      "secret-ingredients-grandmother-taught-me",
      "perfect-pair-idli-podi-combinations",
    ],
  },
  "secret-ingredients-grandmother-taught-me": {
    title: "Secret Ingredients My Grandmother Taught Me",
    excerpt:
      "Family recipes hold treasures beyond taste. Discover the secret ingredients that make traditional South Indian cooking so special.",
    content: [
      "Growing up in a traditional Tamil household, the kitchen was the heart of our home. My grandmother, whom we called Paati, would spend hours creating dishes that filled our home with the most incredible aromas. It wasn't until much later that I understood the secret ingredients she used weren't always about what went into the food.",
      "The first secret she shared was patience. 'Good food takes time,' she would say, slowly stirring a pot of sambar that had been simmering for hours. In our instant-gratification world, this lesson feels more relevant than ever. The slow extraction of flavors from spices, the gradual melding of ingredients—these cannot be rushed.",
      "Her second secret was love. It sounds clichéd, but there's science behind it. When you cook with attention and care, you notice when spices need to be taken off the heat, when the tamarind has balanced perfectly with the jaggery, when the curry leaves have released their full fragrance.",
      "Then there were the actual ingredients. She always kept a small container of homemade ghee, made from the cream skimmed off boiled milk over several days. This ghee, with its rich, nutty flavor, transformed simple dishes into extraordinary ones. 'Store-bought ghee doesn't compare,' she'd say, and she was right.",
      "Fresh curry leaves, picked from the plant in our backyard, were non-negotiable. The difference between fresh and dried curry leaves is like night and day. She would add them at the end of cooking, letting them sizzle in hot oil for just a few seconds—enough to release their aroma without losing their vibrant green color.",
      "Perhaps her most valuable secret was knowing when to break the rules. Traditional recipes are guides, not gospels. 'Cook with your senses,' she'd advise. 'Your nose will tell you when the spices are ready. Your eyes will show you when the color is right. Your taste will confirm when the balance is perfect.'",
    ],
    author: "Meera Krishnan",
    date: "January 10, 2025",
    readTime: "6 min read",
    category: "Stories",
    image: "/images/blog/grandmother-kitchen.jpg",
    relatedPosts: [
      "art-of-making-perfect-podi",
      "regional-variations-south-indian-cooking",
    ],
  },
  "health-benefits-traditional-spices": {
    title: "Health Benefits of Traditional South Indian Spices",
    excerpt:
      "Modern science confirms what our ancestors knew: traditional spices offer remarkable health benefits. Explore the healing power of your spice box.",
    content: [
      "The humble Indian spice box, with its array of colorful powders and seeds, is more than a culinary toolkit—it's a medicine cabinet. Modern research increasingly validates what Ayurvedic practitioners have known for millennia: these spices offer remarkable health benefits.",
      "Turmeric, the golden spice, contains curcumin, one of nature's most powerful anti-inflammatory compounds. Studies show it may help with arthritis, heart disease, and even cognitive decline. For best absorption, always combine turmeric with black pepper and a healthy fat like coconut oil.",
      "Fenugreek seeds, commonly used in South Indian cooking, have been shown to help regulate blood sugar levels. They're particularly beneficial for those managing diabetes. Soaking them overnight and consuming them first thing in the morning is a traditional remedy that science now supports.",
      "The humble curry leaf, often overlooked in favor of more glamorous spices, is a nutritional powerhouse. Rich in vitamins A, B, C, and E, plus minerals like iron and calcium, curry leaves support everything from hair health to digestive function. Their antioxidant properties help combat oxidative stress.",
      "Mustard seeds, essential in South Indian tempering, contain selenium and omega-3 fatty acids. They have antimicrobial properties and may help reduce inflammation. The traditional practice of tempering with mustard seeds in hot oil helps release these beneficial compounds.",
      "Black pepper, often called the 'king of spices,' enhances the bioavailability of other nutrients. It stimulates digestive enzymes and may help with nutrient absorption. In Ayurveda, it's considered 'digestive fire'—essential for proper metabolism.",
    ],
    author: "Dr. Priya Raman",
    date: "January 5, 2025",
    readTime: "7 min read",
    category: "Health",
    image: "/images/blog/spices-health.jpg",
    relatedPosts: [
      "ayurveda-meets-modern-kitchen",
      "art-of-making-perfect-podi",
    ],
  },
  "regional-variations-south-indian-cooking": {
    title: "Regional Variations in South Indian Cooking",
    excerpt:
      "From Tamil Nadu to Kerala, explore how geography, culture, and local ingredients shape the diverse cuisines of South India.",
    content: [
      "South India isn't a monolith—it's a tapestry of four distinct states, each with its own culinary identity shaped by geography, climate, and cultural history. Understanding these regional variations deepens our appreciation for the complexity of South Indian cuisine.",
      "Tamil Nadu, known for its temple towns and Chettinad region, offers bold, spicy flavors. Chettinad cuisine, in particular, is famous for its use of freshly ground spices like kalpasi (stone flower) and marathi mokku (dried flower pods). The food is designed to be intensely flavorful, often featuring black pepper, star anise, and fennel.",
      "Kerala, the land of coconuts and backwaters, has a cuisine that's gentler but no less complex. Coconut in all forms—fresh, dried, oil, milk—forms the backbone of most dishes. The Syrian Christian community contributes dishes like beef fry and appam, while the Malabar coast offers its famous biryanis and seafood preparations.",
      "Karnataka presents a fascinating blend. The northern part shows Mughal influences, while the coastal Mangalore region offers unique preparations like Neer Dosa and Kane Fish Fry. Udupi, a small town, has given the world its famous vegetarian cuisine, including the humble masala dosa.",
      "Andhra Pradesh and Telangana are known for their fiery cuisine. Guntur, famous for its chilies, influences much of the region's cooking. The use of tamarind is more pronounced here, creating a distinctive sour-spicy profile. Pickles from this region are particularly renowned for their heat and complexity.",
      "Despite these differences, certain elements unite South Indian cooking: the importance of rice, the use of tamarind and coconut, the tradition of tempering with mustard seeds and curry leaves, and the philosophy of balancing six tastes—sweet, sour, salty, bitter, pungent, and astringent—in every meal.",
    ],
    author: "Anand Krishnamurthy",
    date: "December 28, 2024",
    readTime: "9 min read",
    category: "Culture",
    image: "/images/blog/regional-cooking.jpg",
    relatedPosts: [
      "secret-ingredients-grandmother-taught-me",
      "art-of-making-perfect-podi",
    ],
  },
};

interface BlogPageProps {
  params: Promise<{ slug: string }>;
}

// Generate static params for all blog posts
export function generateStaticParams() {
  return Object.keys(blogPosts).map((slug) => ({
    slug,
  }));
}

// Generate metadata for each blog post
export async function generateMetadata({ params }: BlogPageProps) {
  const { slug } = await params;
  const post = blogPosts[slug];
  if (!post) {
    return {
      title: "Post Not Found | House of Kumaran Blog",
    };
  }
  return {
    title: `${post.title} | House of Kumaran Blog`,
    description: post.excerpt,
  };
}

export default async function BlogPostPage({ params }: BlogPageProps) {
  const { slug } = await params;
  const post = blogPosts[slug];

  if (!post) {
    return (
      <main className="min-h-screen bg-[#0d1f14] text-[#f5f0e1]">
        <Navbar />
        <section className="pt-32 pb-20 px-6">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="font-serif text-4xl font-bold mb-4">
              Post Not Found
            </h1>
            <p className="text-[#f5f0e1]/60 mb-8">
              The blog post you&apos;re looking for doesn&apos;t exist.
            </p>
            <Link
              href="/blog"
              className="inline-flex items-center gap-2 px-6 py-3 bg-[#b8860b] text-[#0d1f14] font-semibold rounded-full hover:bg-[#d4a017] transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Blog
            </Link>
          </div>
        </section>
        <Footer />
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#0d1f14] text-[#f5f0e1]">
      <Navbar />

      {/* Header */}
      <section className="pt-32 pb-8 px-6">
        <div className="max-w-3xl mx-auto">
          <Link
            href="/blog"
            className="inline-flex items-center gap-2 text-[#b8860b] hover:text-[#d4a017] transition-colors mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Blog
          </Link>

          <span className="inline-block px-3 py-1 bg-[#b8860b]/20 text-[#b8860b] text-sm rounded-full mb-4">
            {post.category}
          </span>

          <h1 className="font-serif text-3xl md:text-5xl font-bold mb-6 leading-tight">
            {post.title}
          </h1>

          <div className="flex flex-wrap items-center gap-4 text-sm text-[#f5f0e1]/60">
            <span className="font-medium text-[#f5f0e1]">{post.author}</span>
            <span className="flex items-center gap-1">
              <Calendar className="w-4 h-4" />
              {post.date}
            </span>
            <span className="flex items-center gap-1">
              <Clock className="w-4 h-4" />
              {post.readTime}
            </span>
          </div>
        </div>
      </section>

      {/* Featured Image Placeholder */}
      <section className="pb-8 px-6">
        <div className="max-w-4xl mx-auto">
          <div className="aspect-[2/1] bg-gradient-to-br from-[#b8860b]/20 to-[#1a472a]/20 rounded-3xl" />
        </div>
      </section>

      {/* Content */}
      <section className="pb-12 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="prose prose-lg prose-invert max-w-none">
            {post.content.map((paragraph, index) => (
              <p key={index} className="text-[#f5f0e1]/80 mb-6 leading-relaxed">
                {paragraph}
              </p>
            ))}
          </div>
        </div>
      </section>

      {/* Share Section */}
      <section className="pb-12 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center justify-between py-6 border-t border-b border-[#b8860b]/10">
            <span className="font-medium">Share this article</span>
            <div className="flex items-center gap-3">
              <a
                href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(
                  `https://houseofkumaran.com/blog/${slug}`
                )}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-[#b8860b]/10 flex items-center justify-center hover:bg-[#b8860b] hover:text-[#0d1f14] transition-colors"
              >
                <Facebook className="w-5 h-5" />
              </a>
              <a
                href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(
                  post.title
                )}&url=${encodeURIComponent(
                  `https://houseofkumaran.com/blog/${slug}`
                )}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-[#b8860b]/10 flex items-center justify-center hover:bg-[#b8860b] hover:text-[#0d1f14] transition-colors"
              >
                <Twitter className="w-5 h-5" />
              </a>
              <a
                href={`https://www.linkedin.com/shareArticle?mini=true&url=${encodeURIComponent(
                  `https://houseofkumaran.com/blog/${slug}`
                )}&title=${encodeURIComponent(post.title)}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-10 h-10 rounded-full bg-[#b8860b]/10 flex items-center justify-center hover:bg-[#b8860b] hover:text-[#0d1f14] transition-colors"
              >
                <Linkedin className="w-5 h-5" />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* Author Bio */}
      <section className="pb-16 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="p-6 bg-[#1a472a]/20 rounded-2xl border border-[#b8860b]/10">
            <div className="flex items-start gap-4">
              <div className="w-16 h-16 rounded-full bg-[#b8860b]/20 flex items-center justify-center flex-shrink-0">
                <span className="font-serif text-2xl text-[#b8860b]">
                  {post.author.charAt(0)}
                </span>
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-1">{post.author}</h3>
                <p className="text-[#f5f0e1]/60 text-sm">
                  A passionate food writer exploring the rich culinary heritage
                  of South India. When not writing, you&apos;ll find them in the
                  kitchen experimenting with traditional recipes.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Related Posts */}
      {post.relatedPosts.length > 0 && (
        <section className="py-16 px-6 bg-[#0a1810]">
          <div className="max-w-[1400px] mx-auto">
            <h2 className="font-serif text-2xl font-bold mb-8">
              Related Articles
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              {post.relatedPosts.map((slug) => {
                const relatedPost = blogPosts[slug];
                if (!relatedPost) return null;
                return (
                  <Link
                    key={slug}
                    href={`/blog/${slug}`}
                    className="group p-6 bg-[#0d1f14] rounded-2xl border border-[#b8860b]/10 hover:border-[#b8860b]/30 transition-colors"
                  >
                    <span className="text-xs text-[#b8860b] uppercase tracking-wider">
                      {relatedPost.category}
                    </span>
                    <h3 className="font-semibold text-lg mt-2 mb-3 group-hover:text-[#b8860b] transition-colors">
                      {relatedPost.title}
                    </h3>
                    <p className="text-[#f5f0e1]/60 text-sm line-clamp-2">
                      {relatedPost.excerpt}
                    </p>
                    <span className="inline-flex items-center gap-1 text-[#b8860b] text-sm mt-4 group-hover:gap-2 transition-all">
                      Read More <ArrowRight className="w-4 h-4" />
                    </span>
                  </Link>
                );
              })}
            </div>
          </div>
        </section>
      )}

      {/* CTA */}
      <section className="py-16 px-6">
        <div className="max-w-3xl mx-auto text-center">
          <h2 className="font-serif text-2xl font-bold mb-4">
            Ready to Taste Tradition?
          </h2>
          <p className="text-[#f5f0e1]/60 mb-6">
            Experience the authentic flavors we write about. Shop our collection
            of traditional South Indian products.
          </p>
          <Link
            href="/shop"
            className="inline-flex items-center gap-2 px-6 py-3 bg-[#b8860b] text-[#0d1f14] font-semibold rounded-full hover:bg-[#d4a017] transition-colors"
          >
            Shop Now
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </section>

      <Footer />
    </main>
  );
}
